- name: Deploy App to Droplet
  hosts: all
  become: yes

  vars: 
    gh_actor: "{{ lookup('env', 'GITHUB_ACTOR') }}"
    gh_token: "{{ lookup('env', 'GITHUB_TOKEN') }}"

  tasks:
    - name: Login to GHCR
      docker_login:
        registry_url: ghcr.io
        username: "{{ gh_actor }}"
        password: "{{ gh_token }}"

    - name: Deploy App
      docker_container:
        name: "ansible-test-container"
        image: "ghcr.io/amifsud02/ansible-test:latest"
        state: started
        restart: yes
        restart_policy: "always"
